// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sluqxmjkizdnstsavsvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdXF4bWpraXpkbnN0c2F2c3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NzAzOTIsImV4cCI6MjA1MzA0NjM5Mn0.zaUaRp-fMzOxmXnuTFUtIFIp6QYLEkduD_avYVgbV9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);